version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: openjdk:8
        environment:
          SBT_VERSION: 1.2.8
      - image: circleci/postgres:9.6.14-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pdesignexer_test
    steps:
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Flyway migrate
          command: sbt "test:flywayMigrate"
      - run:
          name: Test for guice
          command: sbt ";project byGuice; test"
      - run:
          name: Test for free monad
          command: sbt ";project freeMonad; test"
      - run:
          name: Test fot tagless final
          command: sbt ";project taglessFinal; test"
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"